## 모듈과 패키지

In [2]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
# 패키지는 여러 모듈을 묶은 것 (폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [3]:
import math # math라는 모듈이 있어요
print(math.pi)
print(math.sqrt(4)) # sqrt는 제곱근 구해줌

3.141592653589793
2.0


In [4]:
import math as m # math를 가져오는 데 m 이라는 이름으로 가져온다
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [5]:
from math import pi, sqrt
print(pi) # math.pi 는 오히려 안됨
print(sqrt(4))

3.141592653589793
2.0


In [6]:
from math import * # * 이 all 이란 뜻
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [7]:
from math import sqrt as s
print(s(4))

2.0


In [8]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [9]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [10]:
import numpy as np # numpy는 라이브러리(패키지와 모듈들을 모아놓음)다 (numerical python)
a=np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
import numpy.random
numpy.random.randn(3,3) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

array([[-1.61745231, -0.1314394 , -0.4981445 ],
       [ 0.95770658,  0.47166037,  0.57451499],
       [-0.45361739,  0.67274056, -0.85514299]])

In [12]:
import numpy.random as nr
nr.randn(3,3)

array([[ 0.38408165,  0.36066395, -0.37572119],
       [ 2.13808044, -0.89184403, -0.08588212],
       [-0.09357205, -1.51853837,  0.20051003]])

In [13]:
from numpy.random import randn
randn(3,3)

array([[-3.08603302, -1.56390233, -1.08678506],
       [-0.03591224, -0.94274228,  0.27006817],
       [ 1.87825652,  0.95420647, -0.50622966]])

In [14]:
from numpy.random import *
rand(3,3) # uniform distribution

array([[0.75562201, 0.78074808, 0.34645506],
       [0.80024933, 0.32310966, 0.07953475],
       [0.72713325, 0.79575328, 0.34326283]])

In [15]:
from numpy.random import randn as rn
rn(3,3)

array([[ 0.32450821,  0.94435911, -0.57110724],
       [ 1.37995017, -0.19519845,  2.43090846],
       [ 0.63933871,  0.62489017,  1.46018497]])

In [16]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[-1.88131625 -0.41605164  0.10857931]
 [ 0.71973387 -1.52939011  0.02532643]
 [ 0.61412274 -1.00049768 -0.41240306]]
[[0.01185908 0.50832913 0.42434865]
 [0.37706827 0.3860401  0.91922213]
 [0.40407336 0.97778897 0.37820325]]


## numpy 본격적으로

In [17]:
import numpy as np
a=np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=np.array([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64
[1.  2.  3.1 4. ]


In [18]:
A=np.array([[1,2,3],[3,4,5]]) # 이 셀부터는 import numpy as np 는 실행 했다 치고 작성
# A=np.array([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의 수

[[1 2 3]
 [3 4 5]]
(2, 3)
2
6


In [19]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros((3,3))) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0 에서부터 1 포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!

[5 7 9]


In [21]:
A=np.array([[1,2,3],[1,2,3]])
B=np.array([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [22]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## numpy 의 인덱싱과 슬라이싱

In [23]:
a=np.array([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [43]:
# 행렬에 대한 인덱싱과 슬라이싱
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
[4 5 6]
[4 6]
[3 6 9]


In [44]:
# 3차원 행렬 인덱싱
A=np.array([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape)
print(A[0,1,2])

a=np.array([[[1,2,3,4]]]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6
(1, 1, 4)


In [26]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A>3] = 100
print(A) # 그러면 이런 것도 가능하다! (3보다 큰 애들을 100으로 바꿔줘)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=np.array([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2   3 100]
 [100   3 100   3]]
[[1 2]
 [7 8]]
[1 2]


In [27]:
# array로 인덱싱
a=np.array([1,2,3,4,5])
A=a[2]
print(A)
A=a[ np.array(2) ] # np.array를 안에다가?
print(A)
A=a[ np.array([2,3,4]) ]
print(A)
A=a[ np.array([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=np.array([[1,2,3],[4,5,6]])
print(a[0])
A=a[ np.array([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = array([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

3
3
[3 4 5]
[[3 3 3]
 [4 4 4]]
[1 2 3]
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [4 5 6]]]


In [45]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ array(bool) ] => A와 같은 shape을 가지는 array형 bool이 어디에 True를 가지고 있냐
print(A[ np.array([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ array ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ np.array([1,1,2,2,2]) ])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
[2]
[2]
[2]
[[3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]


## numpy의 여러 함수들

In [46]:
A=np.random.randn(3,3) # 여긴 튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들 # 내 필기용

[[-0.30658897  0.28635368  0.03376301]
 [-0.5178321   0.17014448 -0.10207196]
 [-1.70340109  0.11565952  0.17297407]]
[[0.49243143 0.32059899 0.72556028]
 [0.34122382 0.87123459 0.60755418]
 [0.14950483 0.36276218 0.21078418]]
[[-0.30658897  0.28635368  0.03376301]
 [-0.5178321   0.17014448 -0.10207196]
 [-1.70340109  0.11565952  0.17297407]]


In [47]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) = e^1
print(np.log10(10))
print(np.log2(2))
print(np.round(A)) # 반올림
print(np.round(A,2)) # 소수점 둘째자리까지
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[ 0.11078521  0.60174829  0.59603238]
 [ 0.42571241 -0.05373125  1.41520947]
 [-0.75911303  0.20203784 -0.90035324]]
[[0.11078521 0.60174829 0.59603238]
 [0.42571241 0.05373125 1.41520947]
 [0.75911303 0.20203784 0.90035324]]
[[0.33284412 0.77572437 0.77203134]
 [0.65246641 0.23180003 1.18962577]
 [0.87127093 0.4494862  0.94886945]]
[[1.11715493 1.82530718 1.81490366]
 [1.53068051 0.94768676 4.11734885]
 [0.46808142 1.22389432 0.40642607]]
[[-2.200162   -0.50791604 -0.51746028]
 [-0.85399124 -2.92376043  0.34727756]
 [-0.2756046  -1.59930025 -0.10496811]]
1.0
1.0
1.0
[[ 0.  1.  1.]
 [ 0. -0.  1.]
 [-1.  0. -1.]]
[[ 0.11  0.6   0.6 ]
 [ 0.43 -0.05  1.42]
 [-0.76  0.2  -0.9 ]]
[[ 0.  0.  0.]
 [ 0. -1.  1.]
 [-1.  0. -1.]]
[[ 1.  1.  1.]
 [ 1. -0.  2.]
 [-0.  1. -0.]]


In [31]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [32]:
np.nan # not a number
# np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [33]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
print(np.max(A,axis=1)) # 1D array로 바꿔버림
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(np.min(A))
print(np.min(A,axis=0))
print(np.min(A,axis=1))
print(np.argmax(A))
print(np.argmax(A,axis=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

[[-0.50060738 -0.02740052 -0.95781451  0.10532711]
 [-0.17712324  2.22440341 -0.78971358 -0.6569764 ]
 [-0.45371568 -0.89446216  0.57765894  1.30635986]]
2.224403414414483
[-0.17712324  2.22440341  0.57765894  1.30635986]
[0.10532711 2.22440341 1.30635986]
[[-0.17712324  2.22440341  0.57765894  1.30635986]]
[[0.10532711]
 [2.22440341]
 [1.30635986]]
-0.9578145141919996
[-0.50060738 -0.89446216 -0.95781451 -0.6569764 ]
[-0.95781451 -0.78971358 -0.89446216]
5
[1 1 2 2]
[3 1 3]


In [34]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

a=np.random.randn(6,1)
print(a)
print(a.sort(axis=0))

print(np.max(a))
print(a.max())

[[ 0.41119612]
 [ 1.61700111]
 [ 1.72236705]
 [-0.11267728]
 [-0.63586377]
 [ 0.50352467]]
[[-0.63586377]
 [-0.11267728]
 [ 0.41119612]
 [ 0.50352467]
 [ 1.61700111]
 [ 1.72236705]]
[[ 1.72236705]
 [ 1.61700111]
 [ 0.50352467]
 [ 0.41119612]
 [-0.11267728]
 [-0.63586377]]
[[-0.61735785]
 [-2.44697405]
 [ 1.8602477 ]
 [ 1.65973558]
 [ 0.4004347 ]
 [ 2.11421477]]
None
2.1142147672624287
2.1142147672624287


In [35]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1,keepdims=True))
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True))
print(np.std(A)) # standard deviation 표준 편차

print(A.sum(axis=1, keepdims=True))
print(A.mean(axis=1, keepdims=True))
print(A.std())

[[ 1.54381045  0.76625545  1.25123123  0.57664536]
 [-0.42747096 -0.41064231 -0.57555395 -1.14998862]
 [ 0.31903559 -0.56093214 -0.93491514  0.40731967]]
0.8047946402866375
[ 4.1379425  -2.56365584 -0.76949202]
[[ 4.1379425 ]
 [-2.56365584]
 [-0.76949202]]
0.06706622002388646
[ 1.03448562 -0.64091396 -0.192373  ]
[[ 1.03448562]
 [-0.64091396]
 [-0.192373  ]]
0.8304678377836144
[[ 4.1379425 ]
 [-2.56365584]
 [-0.76949202]]
[[ 1.03448562]
 [-0.64091396]
 [-0.192373  ]]
0.8304678377836144


In [36]:
A=np.random.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

[4 4 2 4 1 3 1 4 3 1 4 4]
(12,)
[[[4 4 2]
  [4 1 3]]

 [[1 4 3]
  [1 4 4]]]
3


In [37]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(np.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A=np.random.randn(4,3,6)
print(A.transpose(0,2,1).shape)

9
[[9]]
[[9]]
(4, 6, 3)


In [38]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [39]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [40]:
A=np.ones((3,4))
B=np.zeros((3,4))
C=np.vstack([A,B])
D=np.hstack([A,B])
E=np.block([[A],[B]])
F=np.block([A,B])
G=np.block([ [[A]], [[B]] ])

print(C)
print(D)
print(E)
print(F)
print(G)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [41]:
A = np.random.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,4,5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [42]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...] # np.newaxis is None <- True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape)
A2 = np.expand_dims(A,axis=2)
print(A2.shape)
A3 = np.expand_dims(A,axis=1)
print(A3.shape)
A1 = A.reshape(1,3,4)
print(A1.shape)
A2 = A.reshape(3,4,1)
print(A2.shape)
A3 = A.reshape(3,1,4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
